Global:
  debug: false
  use_gpu: true
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/acn_tiny_exp
  save_epoch_step: 10
  eval_batch_step:
  - 0
  - 1500
  cal_metric_during_train: false
  checkpoints: null
  pretrained_model: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./checkpoints/det_db/predicts_db.txt
  distributed: true
Architecture:
  model_type: det
  algorithm: DB
  Transform: null
  Backbone:
    name: PPLCNetV4_det_acn_tiny
    num_dw_branches: 3
    use_acnet: true
    num_pw_branches: 3
  Neck:
    name: DWRSEFPN
    out_channels: 64
    dilated_kernel_size: 5
  Head:
    name: DBHead
    k: 50
Loss:
  name: DBLoss
  main_loss_type: TverskyLoss
  alpha: 5
  beta: 10
  tversky_alpha: 0.3
  tversky_beta: 0.7
  aux_weight_p4: 0.2
  aux_weight_p3: 0.3
  aux_weight_p2: 0.4
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 2
  regularizer:
    name: CosineL2
    factor: 5.0e-05
    end_factor: 1.0e-06
    warmup_epoch: 2
PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5
Metric:
  name: DetMetric
  main_indicator: hmean
Train:
  dataset:
    name: SimpleDataSet
    data_dir: ../OCR_det
    label_file_list:
    - ../OCR_det/zhongce_training_fix_1.6k.txt
    - ../OCR_det/label_train_all_f4_part2.txt
    - ../OCR_det/label_train_all_f4_part3_baiduyun.txt
    - ../OCR_det/label_train_all_f4_part4.txt
    - ../OCR_det/label_train_all_f4_part5_baiduyun.txt
    - ../OCR_det/synth_en_my_clip.txt
    - ../OCR_det/synth_ch_my_clip.txt
    - ../OCR_det/synth_en_my_largeword_clip.txt
    - ../OCR_det/OCR_det_train/label_done/handwrite_ch_haofenshu_choice_1.txt
    - ../OCR_det/OCR_det_train/label_done/table_ocr_bad_cases.txt
    - ../OCR_det/OCR_det_train/label_done/handwrite_en_haofenshu_choice_1.txt
    - ../OCR_det/OCR_det_train/label_done/Japanese_hongen_shu_remove_smallimg.txt
    - ../OCR_det/OCR_det_train/label_done/ancient_text_high_quality.txt
    - ../OCR_det/OCR_det_train/label_done/handwrite_en_choice1.txt
    - ../OCR_det/OCR_det_train/label_done/handwrite_en_choice2.txt
    - ../OCR_det/OCR_det_train/label_done/handwrite_ch_choice1.txt
    - ../OCR_det/OCR_det_train/label_done/handwrite_ch_choice2.txt
    - ../OCR_det/OCR_det_train/label_done/emoji_train.txt
    - ../OCR_det/OCR_det_train/label_done/manhua_choice1.txt
    - ../OCR_det/OCR_det_train/label_done/newspaper_choice1.txt
    - ../OCR_det/OCR_det_train/label_done/newspaper_choice1_split.txt
    - ../OCR_det/OCR_det_train/label_done_zhongce_updated_0127/ancient.txt
    - ../OCR_det/OCR_det_train/label_done_zhongce_updated_0127/art.txt
    - ../OCR_det/OCR_det_train/label_done_zhongce_updated_0127/blur.txt
    - ../OCR_det/OCR_det_train/label_done_zhongce_updated_0127/greek.txt
    - ../OCR_det/OCR_det_train/label_done_zhongce_updated_0127/handwrite_ch.txt
    - ../OCR_det/OCR_det_train/label_done_zhongce_updated_0127/handwrite_en.txt
    - ../OCR_det/OCR_det_train/label_done_zhongce_updated_0127/Japanese.txt
    - ../OCR_det/OCR_det_train/label_done_zhongce_updated_0127/pinyin.txt
    - ../OCR_det/OCR_det_train/label_done_zhongce_updated_0127/print_ch.txt
    - ../OCR_det/OCR_det_train/label_done_zhongce_updated_0127/print_en.txt
    - ../OCR_det/OCR_det_train/label_done_zhongce_updated_0127/rotate.txt
    - ../OCR_det/OCR_det_train/label_done_zhongce_updated_0127/table.txt
    - ../OCR_det/OCR_det_train/label_done_zhongce_updated_0127/warp.txt
    ratio_list:
    - 0.084
    - 0.056
    - 0.028
    - 0.056
    - 0.056
    - 0.028
    - 0.056
    - 0.056
    - 0.16
    - 0.16
    - 0.16
    - 0.002
    - 0.002
    - 0.16
    - 0.16
    - 0.16
    - 0.16
    - 0.16
    - 0.16
    - 0.16
    - 0.16
    - 0.16
    - 0.1
    - 0.1
    - 0.06
    - 0.06
    - 0.06
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.04
    - 0.16
    - 0.06
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - CopyPaste: null
    - IaaAugment:
        augmenter_args:
        - type: Fliplr
          args:
            p: 0.5
        - type: Affine
          args:
            rotate:
            - -10
            - 10
        - type: Resize
          args:
            size:
            - 0.5
            - 3
    - EastRandomCropData:
        size:
        - 640
        - 640
        max_tries: 50
        keep_ratio: true
    - MakeBorderMap:
        shrink_ratio: 0.4
        thresh_min: 0.3
        thresh_max: 0.7
        total_epoch: 500
    - MakeShrinkMap:
        shrink_ratio: 0.4
        min_text_size: 8
        total_epoch: 500
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - threshold_map
        - threshold_mask
        - shrink_map
        - shrink_mask
  loader:
    shuffle: true
    drop_last: false
    batch_size_per_card: 8
    num_workers: 8
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ../OCR_det
    label_file_list:
    - ../OCR_det/OCR_det_val/label_done_for_det_train/v4_4_test_dataset.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - DetResizeForTest: null
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - shape
        - polys
        - ignore_tags
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 1
    num_workers: 2
profiler_options: null
